### ISSUE TITLE
syncing should not stop video for all participants

### ISSUE THREAD

**Issue by skorsorg** [iyzana/yt-sync#11]
if someone can't sync in time the video should play for all others and sync the one, who doesn't is in sync afterwards

**Comment by iyzana** [comment]
this has been fixed rudimentary in https://github.com/iyzana/yt-sync/commit/0e40617dac2bb1b4dfe6e4ce6ad90760edeeffba by kicking the unresponsive client on a subsequent `play` event after 20 seconds have passed.
this forces them to reload the page.

a future improvement would be to keep trying to sync the client while the others are watching as you mentioned.
