### ISSUE TITLE
too aggressive timeout

### ISSUE THREAD

**Issue by skorsorg** [iyzana/yt-sync#12]
it timeouts very soon even if all are connected

**Comment by iyzana** [comment]
I forgot to reset the sync timeout once the sync was successful.
I believe https://github.com/iyzana/yt-sync/commit/2d73b93632c58f7470c9479a5fb58e152ab71b81 should fix this.
Let me know if the problem persists.

**Comment by iyzana** [comment]
i assume this is fixed now
